### ISSUE TITLE
Pet CRUD

### ISSUE THREAD

**Issue by Carol-88** [PetCare-Manager/petcare-manager-front#14]
### **Historia de Usuario:**

*Como usuario, quiero poder añadir, ver, editar y eliminar perfiles de mis mascotas para gestionar la información individual de cada una.*

### **Tareas Atomizadas:**

- [ ] - Desarrollar la UI para la pantalla de "Añadir Mascota". #7
- [ ] - Implementar la funcionalidad para editar y eliminar mascotas. #15
- [ ] - Conectar la pantalla de "Listado de Mascotas" con el backend para mostrar las mascotas guardadas. #16
- [ ] - Probar las operaciones CRUD (añadir, ver, editar, eliminar).
